---
description: Send notification on Home Assistant stop
alias: system_shutdown_notification
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: !secret robert_iphone
    data:
      message: Home Assistant is shutting down... Bye!
      data:
        push:
