---
description: Send notification on Home Assistant start
alias: system_start_notification
trigger:
  platform: homeassistant
  event: start
action:
  - service: notify.iphone_robert
    data:
      message: Home Assistant is starting up again 🎉
      data:
        push:
